name: Data Pipeline Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: 
      name: data_pipeline
      url: https://github.com
    steps:
    - uses: actions/checkout@v3
    - name: Build, run and test docker image
      run: ./run-pipeline.sh
